Move unsafe types into System_Unsafe namespace (#24443)
## Description

Most of the types in typesUnsafe are system types. Move all of the
public system types in that file into a namespace instead of reexported
them from InternalTypes.

This reduces the risk of errors like the one below when packages using
tree export types which reference these types.

`error TS2742: The inferred type of 'Inventory' cannot be named without
a reference to
'../node_modules/@fluidframework/tree/lib/internalTypes.js'. This is
likely not portable. A type annotation is necessary.`
 
`/examples/utils/import-testing/src/testExports.ts` has some detail on
this subject.

The name "System_Unsafe" was picked so other colections of system types
could name themselves things like "System_Schema". System is being uses
as a logical scope under which namespaces of system types can exist. As
the namespace itself is marked system, we can rename it later if
desired.

## Breaking Changes

This moves some system types, which could break code invalidly referring
to them. See changeset for details.