build: clean up rogue --local arg to API linting `--local` should only be used when making changes to api reports. Remove it for these no emitting cases which are then more clearly safe to run in CI.
Exception: api-markdown-documenter is left for a future change as that package references an invalid config (and is not run by any pipeline).