[TaskManager] Fix assert error when sending a volunteer op before a complete op is acknowledged (#12269)
## Description

This PR fixes an assert error if `voulnteerForTask()` is called before a pending complete op is acknowledged.
## Reviewer Guidance

Would you expect the behavior in this scenario to be different? Should we ignore the volunteer op in this scenario?

## Any relevant logs or outputs

Before the change the newly added test would throw:

```
Error: Removed complete op id does not match
```

## Other information or known dependencies

[AB#2124](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/2124)