build(odsp-driver): convert to fluid-tsc (#19742)
[AB#7272](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/7272)

The PR is only testing CJS as of now. Unfortunately, we can't test ESM.
While debugging the test failures locally, encountered the following:

```
import { stub } from "sinon";
         ^^^^
SyntaxError: Named export 'stub' not found. The requested module 'sinon' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

To resolve the above CommonJS error related to sinon, had been updated
to its latest version 17.0.1. However, this update led to the following
type error during local debugging:
```
TypeError: ES Modules cannot be stubbed
```

---------

Co-authored-by: Sonali Deshpande <48232592+sonalideshpandemsft@users.noreply.github.com>
Co-authored-by: Sonali Deshpande <sonalivdeshpande96@gmail.com>