Fix assert in VersionedSummarizer (#26034)
## Description

Fix invalid assert.

This used to error with:

> $ pnpm run policy-check:asserts
> ...
> ERROR: Template expressions are not supported in assertions (they'll
be replaced by a short code anyway). Use a string literal instead.
> .../packages/dds/tree/src/shared-tree-core/versionedSummarizer.ts:47

This uses the newish debug message provider to preserve the more
detailed message for debug builds while allowing the production one to
be tagged.