build(client): check exactOptionalPropertyTypes=false (#27566)
Ensure that packages building with `"exactOptionalPropertyTypes": true`
(preferred) also support consumers that type check with
`"exactOptionalPropertyType": false` where an optional property might
exist with `undefined`.

Exception: `presence-runtime` is excluded as it has always been built
with `exactOptionalPropertyTypes` enabled and has errors otherwise.
Likely it can be reworked to not depend on that with some altered checks
- all issues appear to be internal logic anyway.

The `"exactOptionalPropertyType": false` setting was removed from
deprecated `ts-common-config.json` and duplicated into consumers using
best supported `exactOptionalPropertyType` setting. `tools/benchmark`
test was fixed to allow `"exactOptionalPropertyType": true` (implicit)
for the test portion of build.