build: Tag asserts (#14509)
@dannimad ➜ /workspaces/FluidFramework (main) $ flub release -g client
-t minor

========================================================================
ERROR: Asserts were tagged. Please create a PR for the changes and merge
before retrying.
 M packages/runtime/test-runtime-utils/src/assertionShortCodesMap.ts

========================================================================

NEED TO COMMIT LOCAL CHANGES

FIRST:

    Commit the local changes and create a PR targeting the main branch.

NEXT:

After changes are merged, run the following command to continue the
release:

    flub release -g client -t minor