tools(client): workaround fluid-build --worker noise build-tools 0.66 has a regression in `fluid-build` when used in "fast" aka `--worker` mode when running `api-extractor`.
Example:
```shell
@fluidframework/core-interfaces: warning: worker failed with code -1 but succeeded directly 'api-extractor run --config api-extractor/api-extractor-lint-legacy.cjs.json'
ReferenceError: require is not defined
    at apiExtractorWorker (file:node_modules/@fluidframework/build-tools/dist/fluidBuild/tasks/workers/apiExtractorWorker.js:13:30)
    at messageHandler (file:node_modules/@fluidframework/build-tools/dist/fluidBuild/tasks/workers/worker.js:22:25)
    at process.<anonymous> (file:node_modules/@fluidframework/build-tools/dist/fluidBuild/tasks/workers/worker.js:51:9)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:949:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
[ 8/22] ✓ @fluidframework/core-interfaces: api-extractor run --config api-extractor/api-extractor-lint-legacy.cjs.json - 5.495s
```