Fix build of request-handler tests (#13671)
## Description

This adds `@node/types` to
`packages/framework/request-handler/src/test/tsconfig.json` to fix the
build error in
`packages/framework/request-handler/src/test/requestHandlers.spec.ts`

Without this, `import { strict as assert } from "assert";` gets typed as
`any` which makes `assert.equal` unable to narrow types resulting in a
type error.

```
@fluidframework/request-handler: error during command 'tsc --project ./src/test/tsconfig.json'
@fluidframework/request-handler: src/test/requestHandlers.spec.ts:95:26 - error TS2532: Object is possibly 'undefined'.
@fluidframework/request-handler: 
@fluidframework/request-handler: 95             assert.equal(response.value.route, "/route");
@fluidframework/request-handler:                             ~~~~~~~~
@fluidframework/request-handler: 
@fluidframework/request-handler: 
@fluidframework/request-handler: Found 1 error.
INFO: [  5/63] x @fluidframework/request-handler: tsc --project ./src/test/tsconfig.json - 0.502s
```

Its currently unclear how the code dot into this broken state, but this
fixes it.