build-tools: bundle size test sanity check (#10508)
Follow up to PR #10502, where we broke the bundle size test.

This change updates the tools to include some sanity check by processing the generated stats file and error if the asset size being tested is smaller than certain threshold (currently set at 100 bytes).

Note that the build tool package will need to be published and updated in the core packages mono repo before this will take effect.

Example output of the tool if the fix for #10502 is removed:
```
found bundleAnalysis for @fluid-example/bundle-size-tests
@fluid-example/bundle-size-tests: asset aqueduct.js (23) is too small
@fluid-example/bundle-size-tests: asset connectionState.js (23) is too small
@fluid-example/bundle-size-tests: asset containerRuntime.js (23) is too small
@fluid-example/bundle-size-tests: asset loader.js (23) is too small
@fluid-example/bundle-size-tests: asset map.js (23) is too small
@fluid-example/bundle-size-tests: asset matrix.js (23) is too small
@fluid-example/bundle-size-tests: asset odspDriver.js (23) is too small
@fluid-example/bundle-size-tests: asset odspPrefetchSnapshot.js (23) is too small
@fluid-example/bundle-size-tests: asset sharedString.js (23) is too small
Error: Found assets are too small (<100 bytes). Webpack bundle analysis is probably not correct.
```