build(protocol-definitions): use node16 module resolution (#20184)
Generated code for type tests needs to add a .js extension:
```
[build:esnext] src/test/types/validateProtocolDefinitionsPrevious.generated.ts:10:31 - error TS2835: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../../index.js'?
[build:esnext] 
[build:esnext] 10 import type * as current from "../../index";
[build:esnext]                                  ~~~~~~~~~~~~~
[build:esnext] 
[build:esnext] 
[build:esnext] Found 1 error in src/test/types/validateProtocolDefinitionsPrevious.generated.ts:10
[build:esnext] 
[build:esnext] npm run build:esnext exited with code 2
```

Semi-automatic PR to switch to node16 module resolution

---------

Co-authored-by: Tyler Butler <tyler@tylerbutler.com>
Co-authored-by: Tyler Butler <tylerbu@microsoft.com>