refactor: Update puppeteer to latest version to address CVE (#22898)
## Description

Update puppeteer to latest version so it brings in `ws@8.17.x` (instead
of `8.16`) to address https://nvd.nist.gov/vuln/detail/CVE-2024-37890.

The [breaking changes from `puppeteer` 22 to
23](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-v23.0.0)
don't affect us as far as I can tell, but I had to update
`jest-puppeteer` to its latest version (and it made sense to update
`jest-environment-puppeteer` as well) for jest tests to pass again.
Otherwise I was getting errors like this:

```console
 FAIL  dist/test/jest/buffer.spec.js
  ● Test suite failed to run

    TypeError: global.context.isIncognito is not a function

      at closeContext (node_modules/.pnpm/jest-environment-puppeteer@9.0.2_typescript@5.4.5/node_modules/jest-environment-puppeteer/dist/index.js:210:24)
```