Fix incorrect compare to {} (#14157)
## Description

```
error TS2839: This condition will always return 'false' since JavaScript compares objects by reference, not value.
```

I think this bug might lead to creating search blobs for empty trees, but this code is apparently unused.