build(client): Tag asserts (#14467)
Output after `npm run policy-check:fix` ran clean:

@dannimad ➜ /workspaces/FluidFramework (main) $ flub release -g client
-t minor
========================================================================
ERROR: Asserts were tagged. Please create a PR for the changes and merge
before retrying.
 M packages/dds/tree/src/core/edit-manager/editManager.ts
 M packages/dds/tree/src/feature-libraries/defaultFieldKinds.ts
 M packages/dds/tree/src/feature-libraries/editable-tree/editableTree.ts
M
packages/dds/tree/src/feature-libraries/modular-schema/modularChangeFamily.ts
 M packages/dds/tree/src/feature-libraries/sequence-field/invert.ts
 M packages/dds/tree/src/shared-tree-core/branch.ts
 M packages/dds/tree/src/shared-tree-core/sharedTreeCore.ts
 M packages/loader/container-loader/src/container.ts
 M packages/loader/container-loader/src/containerContext.ts
 M packages/runtime/container-runtime/src/opLifecycle/opCompressor.ts
 M packages/runtime/container-runtime/src/opLifecycle/opSplitter.ts
 M packages/runtime/container-runtime/src/opLifecycle/outbox.ts
 M packages/runtime/test-runtime-utils/src/assertionShortCodesMap.ts
 M packages/tools/replay-tool/src/helpers.ts

========================================================================

NEED TO COMMIT LOCAL CHANGES

FIRST:

    Commit the local changes and create a PR targeting the main branch.

NEXT:

After changes are merged, run the following command to continue the
release:

    flub release -g client -t minor